#!/bin/bash


	rm /mnt/rocksdb/ch3/*
							  
	echo 1 > /proc/sys/vm/drop_caches;
	echo 2 > /proc/sys/vm/drop_caches;
	echo 3 > /proc/sys/vm/drop_caches;

#	echo 'time ./db_bench --benchmarks="filluniquerandom,stats" --use_direct_io_for_flush_and_compaction=true --use_direct_reads=true --num=625000 --db=/mnt/rocksdb --block_size=4096 --verify_checksum=1 --value_size=16384 --compression_type=none --compression_ratio=1 --use_existing_db=0 --max_background_flushes=1 --max_background_compactions=1 --threads=1'
#	time ./db_bench --benchmarks="filluniquerandom,stats" --use_direct_io_for_flush_and_compaction=true --use_direct_reads=true --num=625000 --db=/mnt/rocksdb --block_size=4096 --verify_checksum=1 --value_size=16384 --compression_type=none --compression_ratio=1 --use_existing_db=0 --max_background_flushes=1 --max_background_compactions=1 --threads=1

	echo 'time ./db_bench --benchmarks="fillrandom,stats" --use_direct_io_for_flush_and_compaction=true --use_direct_reads=true --num=625000 --db=/mnt/rocksdb/ch3 --block_size=4096 --verify_checksum=1 --value_size=16384 --compression_type=none --compression_ratio=1 --use_existing_db=0 --max_background_flushes=1 --max_background_compactions=1 --threads=1'
	time ./db_bench --benchmarks="fillrandom,stats" --use_direct_io_for_flush_and_compaction=true --use_direct_reads=true --num=625000 --db=/mnt/rocksdb/ch3 --block_size=4096 --verify_checksum=1 --value_size=16384 --compression_type=none --compression_ratio=1 --use_existing_db=0 --max_background_flushes=1 --max_background_compactions=1 --threads=1

#	echo 'time ./db_bench --benchmarks="fillrandom,stats" --level0_file_num_compaction_trigger=2 --max_bytes_for_level_base=134217728 --max_write_buffer_number=1 --use_direct_io_for_flush_and_compaction=true --use_direct_reads=true --num=625000 --db=/mnt/md0/rocksdb --block_size=4096 --verify_checksum=1 --value_size=16384 --compression_type=none --compression_ratio=1 --use_existing_db=0 --max_background_flushes=1 --max_background_compactions=1 --threads=1 --duration=10'
#	time ./db_bench --benchmarks="fillrandom,stats" --level0_file_num_compaction_trigger=2 --max_bytes_for_level_base=134217728 --max_write_buffer_number=1 --use_direct_io_for_flush_and_compaction=true --use_direct_reads=true --num=625000 --db=/mnt/md0/rocksdb --block_size=4096 --verify_checksum=1 --value_size=16384 --compression_type=none --compression_ratio=1 --use_existing_db=0 --max_background_flushes=1 --max_background_compactions=1 --threads=1 --duration=10
	
#	echo 'time ./db_bench --benchmarks="fillrandom,stats" --level0_file_num_compaction_trigger=2 --max_bytes_for_level_base=134217728 --max_write_buffer_number=1 --use_direct_io_for_flush_and_compaction=true --use_direct_reads=true --num=625000 --db=/mnt/md0/rocksdb --block_size=4096 --verify_checksum=1 --value_size=16384 --compression_type=none --compression_ratio=1 --use_existing_db=0 --max_background_flushes=1 --max_background_compactions=1 --threads=1'
#	time ./db_bench --benchmarks="fillrandom,stats" --level0_file_num_compaction_trigger=2 --max_bytes_for_level_base=134217728 --max_write_buffer_number=1 --use_direct_io_for_flush_and_compaction=true --use_direct_reads=true --num=625000 --db=/mnt/md0/rocksdb --block_size=4096 --verify_checksum=1 --value_size=16384 --compression_type=none --compression_ratio=1 --use_existing_db=0 --max_background_flushes=1 --max_background_compactions=1 --threads=1

#	echo 'time ./db_bench --benchmarks="fillrandom,stats" --max_write_buffer_number=2 --level0_file_num_compaction_trigger=1 --level0_slowdown_writes_trigger=2 --level0_stop_writes_trigger=2 --target_file_size_base=134217728 --write_buffer_size=67108864 --use_direct_io_for_flush_and_compaction=true --use_direct_reads=true --num=625000 --db=/mnt/md0/rocksdb --block_size=4096 --verify_checksum=1 --value_size=16384 --compression_type=none --compression_ratio=1 --use_existing_db=0 --max_background_flushes=1 --max_background_compactions=1 --threads=1 --duration=15'
#	time ./db_bench --benchmarks="fillrandom,stats" --max_write_buffer_number=2 --level0_file_num_compaction_trigger=1 --level0_slowdown_writes_trigger=2 --level0_stop_writes_trigger=2 --target_file_size_base=134217728 --write_buffer_size=134217728 --write_buffer_size=67108864 --use_direct_io_for_flush_and_compaction=true --use_direct_reads=true --num=625000 --db=/mnt/md0/rocksdb --block_size=4096 --verify_checksum=1 --value_size=16384 --compression_type=none --compression_ratio=1 --use_existing_db=0 --max_background_flushes=1 --max_background_compactions=1 --threads=1 --duration=15
	
#	echo 'time ./db_bench --benchmarks="fillrandom,stats" --max_write_buffer_number=2 --level0_file_num_compaction_trigger=1 --level0_slowdown_writes_trigger=2 --level0_stop_writes_trigger=2 --target_file_size_base=134217728 --write_buffer_size=67108864 --use_direct_io_for_flush_and_compaction=true --use_direct_reads=true --num=62500 --db=/mnt/md0/rocksdb --block_size=4096 --verify_checksum=1 --value_size=16384 --compression_type=none --compression_ratio=1 --use_existing_db=0 --max_background_flushes=1 --max_background_compactions=1 --threads=1'
#	time ./db_bench --benchmarks="fillrandom,stats" --max_write_buffer_number=2 --level0_file_num_compaction_trigger=1 --level0_slowdown_writes_trigger=2 --level0_stop_writes_trigger=2 --target_file_size_base=134217728 --write_buffer_size=134217728 --write_buffer_size=67108864 --use_direct_io_for_flush_and_compaction=true --use_direct_reads=true --num=62500 --db=/mnt/md0/rocksdb --block_size=4096 --verify_checksum=1 --value_size=16384 --compression_type=none --compression_ratio=1 --use_existing_db=0 --max_background_flushes=1 --max_background_compactions=1 --threads=1 
